Repository cpp-linter/cpp-linter-action, pull requests merged in 2022-08, with the labels that each got.

#85 Clean-up README (#80)
  README.md
  docs/images/icon.png
  docs/images/icon_large.png
  docs/images/icon_large.xcf
  docs/images/logo.png
  docs/images/logo_nobg.png
  docs/index.md
Labels: documentation

#86 Remove broken logo (#80)
  mkdocs.yml
Labels: bug

#81 Unit tests + coverage reports, type checking, pre-commit, and requested fixes
  .ci-ignore
  .gitattributes
  .github/workflows/mkdocs-deploy.yml
  .github/workflows/pre-commit-hooks.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/run-dev-tests.yml
  .github/workflows/run-pylint.yml
  .github/workflows/run-test.yml
  .gitignore
  .gitpod.yml
  .pre-commit-config.yaml
  .pylintrc
  Dockerfile
  README.md
  action.yml
  cpp_linter/__init__.py
  cpp_linter/clang_format_xml.py
  cpp_linter/clang_tidy.py
  cpp_linter/clang_tidy_yml.py
  cpp_linter/run.py
  cpp_linter/thread_comments.py
  demo/demo.hpp
  docs/requirements.txt
  mkdocs.yml
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/capture_tools_output/.clang-format
  tests/capture_tools_output/.clang-tidy
  tests/capture_tools_output/event_files.json
  tests/capture_tools_output/expected_result.json
  tests/capture_tools_output/test_database_path.py
  tests/capture_tools_output/test_tools_output.py
  tests/ignored_paths/.gitmodules
  tests/ignored_paths/test_ignored_paths.py
  tests/test_cli_args.py
  tests/test_misc.py
Labels: enhancement

#89 Fix add tag failed when more than 1 PR open(#84)
  .github/workflows/run-test.yml
Labels: bug

#90 fix setting of lines-changed-only
  cpp_linter/run.py
  tests/test_cli_args.py
Labels: bug
